sudo: required
dist: trusty
before_install:
- sudo apt-get install texlive-xetex -y
- sudo apt-get install texlive-latex-extra -y
- sudo apt-get install texlive-fonts-recommended -y
script:
- xelatex --interaction=nonstopmode --halt-on-error --jobname=cv cv_12.tex
before_deploy:
  - cp cv.pdf en-GB.pdf
  - cp cv.pdf pt-PT.pdf
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: pt-PT.pdf
  skip_cleanup: true
  on:
    branch: pt
